package lab7;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author frnlpz
 */
public class MainUI extends javax.swing.JFrame {

    LocalDate dateFrom, dateTo = null;
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM-dd-yyyy");

    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        initComponents();
        jLabelErrorFrom.setVisible(false);
        jLabelErrorTo  .setVisible(false);
        this.setTitle("Software for OOP Techniques. Francisco López.");
        this.setName("OOPT Software");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBarFilter = new javax.swing.JToolBar();
        jLabelStudent = new javax.swing.JLabel();
        jComboBoxStudent = new javax.swing.JComboBox<>();
        jLabelDateFrom = new javax.swing.JLabel();
        jTextFieldDateFrom = new javax.swing.JTextField();
        jLabelDateTo = new javax.swing.JLabel();
        jTextFieldDateTo = new javax.swing.JTextField();
        jButtonFilter = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();
        jToolBarError = new javax.swing.JToolBar();
        jLabelErrorFrom = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(75, 10), new java.awt.Dimension(75, 10), new java.awt.Dimension(75, 10));
        jLabelErrorTo = new javax.swing.JLabel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuAdd = new javax.swing.JMenu();
        jMenuItemAddCourse = new javax.swing.JMenuItem();
        jMenuItemAddStudent = new javax.swing.JMenuItem();
        jMenuItemAddPoints = new javax.swing.JMenuItem();
        jMenuLanguage = new javax.swing.JMenu();
        jMenuItemLanguage1 = new javax.swing.JMenuItem();
        jMenuItemLanguage2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBarFilter.setBorder(null);
        jToolBarFilter.setRollover(true);

        jLabelStudent.setText("Student");
        jToolBarFilter.add(jLabelStudent);

        jComboBoxStudent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxStudent.setPreferredSize(new java.awt.Dimension(220, 27));
        jToolBarFilter.add(jComboBoxStudent);

        jLabelDateFrom.setText("Date from: ");
        jToolBarFilter.add(jLabelDateFrom);

        jTextFieldDateFrom.setMinimumSize(new java.awt.Dimension(10, 10));
        jTextFieldDateFrom.setPreferredSize(new java.awt.Dimension(120, 24));
        jTextFieldDateFrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateFromActionPerformed(evt);
            }
        });
        jToolBarFilter.add(jTextFieldDateFrom);

        jLabelDateTo.setText("Date to: ");
        jToolBarFilter.add(jLabelDateTo);

        jTextFieldDateTo.setPreferredSize(new java.awt.Dimension(120, 24));
        jTextFieldDateTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDateToActionPerformed(evt);
            }
        });
        jToolBarFilter.add(jTextFieldDateTo);

        jButtonFilter.setText("Filter");
        jButtonFilter.setFocusable(false);
        jButtonFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFilterActionPerformed(evt);
            }
        });
        jToolBarFilter.add(jButtonFilter);

        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Group, Name, Surname", "Date", "Points", "Description"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResult.setColumnSelectionAllowed(true);
        jTableResult.getTableHeader().setReorderingAllowed(false);
        jScrollPane.setViewportView(jTableResult);
        jTableResult.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jToolBarError.setBorder(null);
        jToolBarError.setRollover(true);

        jLabelErrorFrom.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorFrom.setText("Enter correct date");
        jToolBarError.add(jLabelErrorFrom);

        filler1.setSize(new java.awt.Dimension(75, 10));
        jToolBarError.add(filler1);

        jLabelErrorTo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelErrorTo.setText("Enter correct date");
        jToolBarError.add(jLabelErrorTo);

        jMenuFile.setText("File");

        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuAdd.setText("Add");

        jMenuItemAddCourse.setText("Add new course");
        jMenuAdd.add(jMenuItemAddCourse);

        jMenuItemAddStudent.setText("Add new student");
        jMenuAdd.add(jMenuItemAddStudent);

        jMenuItemAddPoints.setText("Add new act. points");
        jMenuAdd.add(jMenuItemAddPoints);

        jMenuBar.add(jMenuAdd);

        jMenuLanguage.setText("Language");

        jMenuItemLanguage1.setText("English");
        jMenuItemLanguage1.setSelected(true);
        jMenuItemLanguage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLanguage1ActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jMenuItemLanguage1);

        jMenuItemLanguage2.setText("Español");
        jMenuItemLanguage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLanguage2ActionPerformed(evt);
            }
        });
        jMenuLanguage.add(jMenuItemLanguage2);

        jMenuBar.add(jMenuLanguage);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBarFilter, javax.swing.GroupLayout.DEFAULT_SIZE, 702, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToolBarError, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBarFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jToolBarError, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jButtonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFilterActionPerformed
        setDateFrom(jTextFieldDateFrom.getText());
        setDateTo(jTextFieldDateTo.getText());
        System.out.println(dateFrom+"---"+dateTo);          //debugging
    }//GEN-LAST:event_jButtonFilterActionPerformed

    private void jTextFieldDateFromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateFromActionPerformed
        setDateFrom(jTextFieldDateFrom.getText());
    }//GEN-LAST:event_jTextFieldDateFromActionPerformed

    private void jTextFieldDateToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDateToActionPerformed
        setDateTo(jTextFieldDateTo.getText());
    }//GEN-LAST:event_jTextFieldDateToActionPerformed

    private void jMenuItemLanguage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLanguage1ActionPerformed
        this.setTitle("Software for OOP Techniques. Francisco López.");
        this.setName("OOPT Software");
        jButtonFilter.setText("Filter");
        jLabelDateFrom.setText("Date from: ");
        jLabelDateTo.setText("Date to: ");
        jLabelErrorFrom.setText("Enter correct date");
        jLabelErrorTo.setText("Enter correct date");
        jLabelStudent.setText("Student");
        jMenuAdd.setText("Add");
        jMenuFile.setText("File");
        jMenuLanguage.setText("Language");
        jMenuItemAddCourse.setText("Add new course");
        jMenuItemAddPoints.setText("Add new act. points");
        jMenuItemAddStudent.setText("Add new student");
        jMenuItemExit.setText("Exit");
        jMenuItemLanguage1.setText("English");
        jMenuItemLanguage2.setText("Spanish");
        //DUDAS   jTableResult
    }//GEN-LAST:event_jMenuItemLanguage1ActionPerformed

    private void jMenuItemLanguage2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLanguage2ActionPerformed
        this.setTitle("Software para Técnicas de POO. Francisco López.");  
        this.setName("TPOO Software");
        jButtonFilter.setText("Filtrar");
        jLabelDateFrom.setText("Desde: ");
        jLabelDateTo.setText("Hasta: ");
        jLabelErrorFrom.setText("Fecha incorrecta");
        jLabelErrorTo.setText("Fecha incorrecta");
        jLabelStudent.setText("Estudiante");
        jMenuAdd.setText("Añadir");
        jMenuFile.setText("Archivo");
        jMenuLanguage.setText("Idioma");
        jMenuItemAddCourse.setText("Añadir nuevo curso");
        jMenuItemAddPoints.setText("Añadir puntos de acts.");
        jMenuItemAddStudent.setText("Añadir nuevo estudiante");
        jMenuItemExit.setText("Salir");
        jMenuItemLanguage1.setText("Inglés");
        jMenuItemLanguage2.setText("Español");
        //DUDAS   jTableResult
    }//GEN-LAST:event_jMenuItemLanguage2ActionPerformed

    private void setDateFrom(String date){        
        try {
            dateFrom = LocalDate.parse(date, formatter);
            if (jLabelErrorFrom.isVisible()) jLabelErrorFrom.setVisible(false);
        } catch (DateTimeParseException e) {
            System.out.println("Incorrect from date.");     //debugging
            if (!jLabelErrorFrom.isVisible()) jLabelErrorFrom.setVisible(true);
        }
    }
    
    private void setDateTo(String date){
        try {
            dateTo   = LocalDate.parse(date, formatter);
            if (jLabelErrorTo.isVisible()) jLabelErrorTo.setVisible(false);          
        } catch (DateTimeParseException e) {
            System.out.println("Incorrect to date.");       //debugging
            if (!jLabelErrorTo.isVisible()) jLabelErrorTo.setVisible(true);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButtonFilter;
    private javax.swing.JComboBox<String> jComboBoxStudent;
    private javax.swing.JLabel jLabelDateFrom;
    private javax.swing.JLabel jLabelDateTo;
    private javax.swing.JLabel jLabelErrorFrom;
    private javax.swing.JLabel jLabelErrorTo;
    private javax.swing.JLabel jLabelStudent;
    private javax.swing.JMenu jMenuAdd;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemAddCourse;
    private javax.swing.JMenuItem jMenuItemAddPoints;
    private javax.swing.JMenuItem jMenuItemAddStudent;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLanguage1;
    private javax.swing.JMenuItem jMenuItemLanguage2;
    private javax.swing.JMenu jMenuLanguage;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTable jTableResult;
    private javax.swing.JTextField jTextFieldDateFrom;
    private javax.swing.JTextField jTextFieldDateTo;
    private javax.swing.JToolBar jToolBarError;
    private javax.swing.JToolBar jToolBarFilter;
    // End of variables declaration//GEN-END:variables
}
